### ISSUE TITLE
working stack underflow when trying to run badapple.rom

### ISSUE THREAD

**Issue by bicyclesonthemoon** [karolbelina/bad-apple-uxn#1]
Downloaded the released badapple.rom v1.0.1.
When trying to run this error occurs:
```
4.b:~/pro/uxn> uxnemu badapple.rom
Loaded badapple.rom
<wst> empty
<rst> 01 16
Halted: Working-stack underflow#0023, at 0x0130
Boot: Failed to start rom.
Boot: Failed to boot.
4.b:~/pro/uxn>
```

**Comment by karolbelina** [comment]
@bicyclesonthemoon i'm not familiar with recent uxn changes so i'm not sure what might be the issue, but i'm gonna look into it when i have the time. thanks for noticing

**Comment by karolbelina** [comment]
@bicyclesonthemoon oh, actually it seems to work if you assemble the `badapple.tal` yourself with the most recent version of `uxnasm`
```console
$ uxnasm badapple.tal badapple_fixed.rom
Assembled badapple_fixed.rom in 63437 bytes(97.18% used), 46 labels, 9 macros.
$ uxnemu badapple_fixed.rom
Loaded badapple_fixed.rom
```

but i'm still going to release a new version with the new ROM. thank you!
